### ISSUE TITLE
nodemon conflicts 

### ISSUE THREAD

**Issue by lucasabrantes1** [japa/core#43]
I'm trying to perform tests and through a custom script by nodemon, when I try to run the command I created japa:watch, it manages to run the test but right after the error below, I tried to remove the folder node modules and install again, but none of that worked

![image](https://user-images.githubusercontent.com/62405928/135185035-2ed4d29b-ea29-4d70-9b3d-91bcc6a02175.png)

_**package json command that iam trying to change to use with nodeman
**_
```
"japa": "node -r @adonisjs/assembler/build/register japaFile.ts",
    "japa:watch": "nodemon --watch 'test/specs/**/*' --ext json,ts --exec npm run japa --quiet"
```

**## Package version**
```
npm: '6.14.15',
node: '14.17.6',
```

## Error Message & Stack Trace
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! facebook-api@1.0.0 japa: `node -r @adonisjs/assembler/build/register japaFile.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the facebook-api@1.0.0 japa script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lucas\AppData\Roaming\npm-cache\_logs\2021-09-29T00_46_54_039Z-debug.log
```

Logs

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'japa'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prejapa', 'japa', 'postjapa' ]
5 info lifecycle facebook-api@1.0.0~prejapa: facebook-api@1.0.0
6 info lifecycle facebook-api@1.0.0~japa: facebook-api@1.0.0
7 verbose lifecycle facebook-api@1.0.0~japa: unsafe-perm in lifecycle true
8 verbose lifecycle facebook-api@1.0.0~japa: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Lucas\www\facebook-api\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Lucas\www\facebook-api\node_modules\.bin;C:\Users\Lucas\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Lucas\bin;C:\Python39\Scripts;C:\Python39;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn;C:\Program Files\Microsoft SQL Server\150\Tools\Binn;C:\Program Files\Microsoft SQL Server\150\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn;C:\Program Files\Azure Data Studio\bin;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\Lucas\AppData\Local\Microsoft\WindowsApps;C:\Users\Lucas\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\Lucas\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle facebook-api@1.0.0~japa: CWD: C:\Users\Lucas\www\facebook-api
10 silly lifecycle facebook-api@1.0.0~japa: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'node -r @adonisjs/assembler/build/register japaFile.ts'
10 silly lifecycle ]
11 silly lifecycle facebook-api@1.0.0~japa: Returned: code: 1  signal: null
12 info lifecycle facebook-api@1.0.0~japa: Failed to exec japa script
13 verbose stack Error: facebook-api@1.0.0 japa: `node -r @adonisjs/assembler/build/register japaFile.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid facebook-api@1.0.0
15 verbose cwd C:\Users\Lucas\www\facebook-api
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "japa"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error facebook-api@1.0.0 japa: `node -r @adonisjs/assembler/build/register japaFile.ts`
22 error Exit status 1
23 error Failed at the facebook-api@1.0.0 japa script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by thetutlage** [comment]
To me it looks like an assertion failed in the test ( as per the screenshot )

**Comment by lucasabrantes1** [comment]
> To me it looks like an assertion failed in the test ( as per the screenshot )

but right after the elifecycle error

**Comment by thetutlage** [comment]
Closing as it seems likely an un-related error. I recommend upgrading to the newer version and lemme know if you still have issues using Nodemon.
