### ISSUE TITLE
Cannot Access Assert from JapaFile.ts

### ISSUE THREAD

**Issue by nelsonjd** [japa/core#51]
## Error Message & Stack Trace
> node -r @adonisjs/assembler/build/register japaFile.ts

I'm trying to run the following commands given in this issue https://github.com/japa/core/issues/9
`Assertion` looks like it has been renamed to `Assert`

`import { Assert } from 'japa/api';`
`import chaiSpies from 'chai-spies';`
`Assert.use(chai-spies)`
```
Error: Cannot find module 'japa/api'
Require stack:
- /Users/projordan/workspace/platform-backend/japaFile.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/projordan/workspace/platform-backend/japaFile.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._compile (/Users/projordan/workspace/platform-backend/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Object.newLoader [as .ts] (/Users/projordan/workspace/platform-backend/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:975:32)
```

**Comment by nelsonjd** [comment]
Solution was `import { Assert } from 'japa/build/api`.
