### ISSUE TITLE
Error in group functions is swallowed and not shown

### ISSUE THREAD

**Issue by maxgalbu** [japa/core#62]
## Description

When an exception is thrown in group.setup(), nothing is shown and the test doesn't run. See the error below:

```js
group.setup(async() => {
    app = await setupApplication();
    await setup(app);
});
```

## Package version
2.0.11

## Error Message & Stack Trace

```
event = "group:end"
payload = [
  {
    phase: 'setup',
    error: Error: Cannot find module '@adonisjs/repl'
    Require stack:
    - /Users/mgalbusera/Documents/development/denise/adonis5-jwt/test-helpers/__app/noop.js
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
        at resolveFileName (/Users/mgalbusera/Documents/development/denise/adonis5-jwt/node_modules/resolve-from/index.js:29:39)
        at resolveFrom (/Users/mgalbusera/Documents/development/denise/adonis5-jwt/node_modules/resolve-from/index.js:43:9)
        at module.exports (/Users/mgalbusera/Documents/development/denise/adonis5-jwt/node_modules/resolve-from/index.js:46:47)
        at Object.resolveFrom (/Users/mgalbusera/Documents/development/denise/adonis5-jwt/node_modules/@poppinss/utils/build/src/Helpers/resolveFrom.js:25:39)
        at Registrar.loadProvider (/Users/mgalbusera/Documents/development/denise/adonis5-jwt/node_modules/@adonisjs/fold/build/src/Registrar/index.js:50:25)
        at Registrar.collect (/Users/mgalbusera/Documents/development/denise/adonis5-jwt/node_modules/@adonisjs/fold/build/src/Registrar/index.js:68:59)
        at Registrar.register (/Users/mgalbusera/Documents/development/denise/adonis5-jwt/node_modules/@adonisjs/fold/build/src/Registrar/index.js:97:9)
        at /Users/mgalbusera/Documents/development/denise/adonis5-jwt/node_modules/@adonisjs/application/build/src/Application.js:530:41
        at Application.registerProviders (/Users/mgalbusera/Documents/development/denise/adonis5-jwt/node_modules/@adonisjs/application/build/src/Application.js:524:9) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [Array]
    }
  }
]
```

PS: I don't have @adonisjs/repl since I'm in a library and not an actual app.

**Comment by thetutlage** [comment]
Reopening to debug it locally and see if we can reproduce the same issue

**Comment by thetutlage** [comment]
<img width="1255" alt="Screenshot 2023-06-22 at 1 52 11 PM" src="https://github.com/japa/core/assets/1706381/37144173-9c73-45c5-af71-c5daccc45930">

Just gave it run and it seems to be work fine. Here is a sample repo https://github.com/thetutlage/japa-core-issue-62

**Comment by thetutlage** [comment]
Closing, since not able to reproduce. Feel free to reopen when you have time and still the issue persists
